### ISSUE TITLE
torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1)

### ISSUE THREAD

**Issue by aulaywang** [guoyww/AnimateDiff#319]
```
(animatediff) root@dummmy-20240408200000454-worker-0:/data/code/AnimateDiff# CUDA_VISIBLE_DEVICES=0 torchrun --nnodes=1 --nproc_per_node=1 train.py --config configs/training/v1/image_finetune.yaml                                                                                                            
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .                                                 
04/09/2024 02:10:38 - INFO - root - ***** Running training *****                                                                                                               
04/09/2024 02:10:38 - INFO - root -   Num examples = 4999                                                                                                                      
04/09/2024 02:10:38 - INFO - root -   Num Epochs = 2                                                                                                                           
04/09/2024 02:10:38 - INFO - root -   Instantaneous batch size per device = 50                                                                                                 
04/09/2024 02:10:38 - INFO - root -   Total train batch size (w. parallel, distributed & accumulation) = 50                                                                    
04/09/2024 02:10:38 - INFO - root -   Gradient Accumulation steps = 1                                                                                                          
04/09/2024 02:10:38 - INFO - root -   Total optimization steps = 100                                                                                                           
Steps:   0%|                                                             | 0/100 [00:00<?, ?it/s]Traceback (most recent call last):                                            
  File "/data/code/AnimateDiff/train.py", line 493, in <module>                                                                      
    main(name=name, launcher=args.launcher, use_wandb=args.wandb, **config)
File "/data/code/AnimateDiff/train.py", line 386, in main
    scaler.scale(loss).backward()
  File "/opt/conda/envs/animatediff/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/opt/conda/envs/animatediff/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/envs/animatediff/lib/python3.10/site-packages/torch/autograd/function.py", line 267, in apply
    return user_fn(self, *args)
  File "/opt/conda/envs/animatediff/lib/python3.10/site-packages/torch/autograd/function.py", line 414, in wrapper
    outputs = fn(ctx, *args)
  File "/opt/conda/envs/animatediff/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 111, in backward
    grads = _memory_efficient_attention_backward(
  File "/opt/conda/envs/animatediff/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 382, in _memory_efficient_attention_backward
    grads = op.apply(ctx, inp, grad)
File "/opt/conda/envs/animatediff/lib/python3.10/site-packages/xformers/ops/fmha/cutlass.py", line 184, in apply
    (grad_q, grad_k, grad_v,) = cls.OPERATOR(
  File "/opt/conda/envs/animatediff/lib/python3.10/site-packages/torch/_ops.py", line 442, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Steps:   0%|                                                             | 0/100 [02:38<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 431512) of binary: /opt/conda/envs/animatediff/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/animatediff/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.1', 'console_scripts', 'torchrun')())
  File "/opt/conda/envs/animatediff/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
File "/opt/conda/envs/animatediff/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/opt/conda/envs/animatediff/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/envs/animatediff/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/animatediff/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-09_02:13:18
  host      : dummmy-20240408200000454-worker-0
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 431512)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

**Comment by aulaywang** [comment]
I have solved this problem.
Need to omit the Line 213-218 of train.py, which about the xformers. Like this:
```
# Enable xformers
# if enable_xformers_memory_efficient_attention:
#     if is_xformers_available():
#         unet.enable_xformers_memory_efficient_attention()
#     else:
#         raise ValueError("xformers is not available. Make sure it is installed correctly")
```
